### ISSUE TITLE
Improve error message if value is not defined in enum

### ISSUE THREAD

**Issue by johannesluedke** [ahx/openapi_first#113]
In the error `{"errors":[{"source":{"pointer":"/data/type"},"title":"is not valid: \"my_type1\""}]}` I have no clues which are the valid values, which would be nice to print in case of an enum so it's easier to find out what error one did when specifying the endpoint in the openapi.yaml

**Comment by ahx** [comment]
Hi @johannesluedke! Thanks for the issue. 
What do you think about [this change](https://github.com/ahx/openapi_first/pull/116/files#diff-c20e4437c39d6e18beba543b313c31eec7fbd111589f98ef92bbfdc7ff5cdb2cR102-R104)? It changes the error to something like:

```json
{
  "errors": [
    {
      "source": {
        "pointer": "/type"
      },
      "title": "value \"unknown-type\" is not defined in enum",
      "detail": "value can be one of pet, plan"
    }
  ]
}
```
