### ISSUE TITLE
Add support for multiple content types 

### ISSUE THREAD

**Issue by johannesluedke** [ahx/openapi_first#117]
Would be nice to be able to have a single route take requests with either json and respond with json, or take requests with json-api and respond with json-api.
This would be really useful f.e. for the transition phase of moving an API endpoint from json to json-api

refs https://stackoverflow.com/a/46696137/1627888, https://github.com/go-swagger/go-swagger/issues/1319

**Comment by ahx** [comment]
Related to https://github.com/ahx/openapi_first/issues/15

**Comment by ahx** [comment]
This should work since 0.2x
