### ISSUE TITLE
What's the best way to validation request/responses without using the router (in Rails)?

### ISSUE THREAD

**Issue by twe4ked** [ahx/openapi_first#140]
Hey,

We're currently (slowly) adding OpenAPI for request/response validation to an existing Rails app. We can't easily switch all the way to adding operations and the router to replace our controllers but I'd like to introduce some middleware to log schema errors so we can build a dashboard to track exceptional cases.

I've had a bit of a poke through the validator and middlewares included in the app but they all seem to reference operations and expect the router to be in place. I'd really appreciate a nudge in the right direction as I'll probably be digging into the private API a bit.

Cheers!

**Comment by ahx** [comment]
Hi,
thanks so much for the feedback. There is [ResponseValidator](https://github.com/ahx/openapi_first/blob/master/lib/openapi_first/response_validator.rb), which can be used for response validation, which we used at work for response validation, but we switched to using the normal [middlewares](https://github.com/ahx/openapi_first#rack-middlewares) instead. But I would really like to remove ResponseValidator.

How about adding the RequestValidation and ResponseValidation middlewares to just one controller at a time and not add it globally to your Rails app? Do you think that would work for you?

Or are you thinking about tracking exceptions silently and don't want to have RequestValidation return a 400 if the request is not valid? Thanks again for the interest in this gem.

**Comment by ahx** [comment]
I was also thinking about removing the necessity to use the Router middleware, which might make implementing your use case a bit easier.

**Comment by twe4ked** [comment]
Thanks for the response. Sorry, I should have added a bit more context with what I've tried:

```ruby
require "openapi_first"

class OpenapiValidation
  API_PATH_PREFIX = "/api/".freeze

  def initialize(app)
    @app = app

    # NOTE: This produces warnings for each endpoint that come from an internal
    # router that's part of OpenapiFirst. It's not relevant for us because
    # we're not using the router.
    Warning.ignore(/operationId is missing in '.*'\. I am ignoring this operation\./)

    spec = OpenapiFirst.load("app/schemas/openapi.yml")
    @openapi_validator = OpenapiFirst::ResponseValidator.new(spec)
  end

  def call(env)
    request = Rack::Request.new(env)
    response = @app.call(env)

    if request.path.starts_with?(API_PATH_PREFIX)
      begin
        @openapi_validator.validate(request, response)
      rescue OpenapiFirst::ResponseBodyInvalidError => e
        raise e unless Rails.env.production?

        MyLogger.log(
          "openapi.request_validation.error",
          path: request.path,
          method: request.env["REQUEST_METHOD"],
          error_message: e.message
        )
      rescue OpenapiFirst::NotFoundError
        # Until we've got more of the API documented we can simply ignore
        # unspecified routes.
      end
    end

    response
  end
end
```

This is the middleware I wrote the other day. The main issue is that `OpenapiFirst::ResponseValidator` requires an operation ID to be set so the router can set `env[OPERATION]`. We could look at adding operation IDs, but AFAICT that shouldn't be required by OpenAPI to validate our request/responses.

As far as removing `ResponseValidator`, I think ideally some API similar to that would remain, as it's lower level it should add more flexibility for people wanting to write their own very specific middleware where they might want to modify responses or simply log issues.

> How about adding the RequestValidation and ResponseValidation middlewares to just one controller at a time and not add it globally to your Rails app? Do you think that would work for you?

This might work, if the middleware was more customizble, such as allowing specifying lambdas to run in error cases. As it is I think I'll still need to write my own. I'd also still be facing the "operation ID" issue.

> Or are you thinking about tracking exceptions silently and don't want to have RequestValidation return a 400 if the request is not valid? 

Yeah, for now we just want to be aware of any issues.

Thanks again!

**Comment by ahx** [comment]
> We could look at adding operation IDs, but AFAICT that shouldn't be required by OpenAPI to validate our request/responses.

Good point! I will remove the check for the operationId. This is only relevant in the Responder part, which you are not using currently.

**Comment by twe4ked** [comment]
That'd be great, thanks!

**Comment by ahx** [comment]
Hi, I've changed a few small things that I wanted to change for some time and that might be helpful for you:

- The warning about missing operationId is gone ✨. (operationId is used only in the (Rack)Responder parts).
- You no longer have to call `OpenapiFirst.load`, but can also pass the path to the OpenAPI file instead
- Adding the "Router" middleware is optional now as it is added automatically (not relevant for your use case, though)

About your actual question: I think using ResponseValidator here make sense the way you use it in the middleware and I agree that we should keep/add a low level API to validate requests/responses or parts of it.

Questions about your use case:
- Do you want to add _request_ validation as well and log issues about that as well?

**Comment by twe4ked** [comment]
Amazing, thanks for the changes 🤩 – I'll update and let you know how I go!

> Do you want to add request validation as well and log issues about that as well?

Yup, we'll definitely want both request and response validation.

**Comment by twe4ked** [comment]
Would it be possible to introduce an API similar to `OpenapiFirst::ResponseValidator#validate` for requests?

**Comment by ahx** [comment]
@twe4ked yes, very much! Do  you  have  any preference how that API should look like?

**Comment by ahx** [comment]
@twe4ked Another option would be to call an instance of the RequestValidator Middleware something like this:

```ruby
request_validator = OpenapiFirst::RequestValidation.new(->(env){}, spec: 'openapi/openapi.yaml', raise_error: true)
request_validator.call(env)
```

This got a bit simpler, because you no longer have to setup "Router".

**Comment by twe4ked** [comment]
Ah yes, that example will work for now, thanks!

As far as API design, I'd probably do something along these lines (naming just for illustration purposes):

```ruby
class RequestValidator
  def call(request:)
    # This would raise exceptions on invalid requests
  end
end

class ResponseValidator
  def call(request:, response:)
    # This would raise exceptions on invalid responses
  end
end

class ResponseValidationMiddleware
  def call(env)
    # uses ResponseValidator and optionally catches errors
  end
end

class RequestValidationMiddleware
  def call(env)
    # uses RequestValidator and optionally catches errors
  end
end
```

That way folks that want to write their own middleware or use the library in different ways have that flexibility and it should keep the middleware quite simple.

**Comment by twe4ked** [comment]
This is what I've ended up with for now:

```ruby
require "openapi_first"

class OpenapiValidation
  API_PATH_PREFIX = "/api/".freeze
  SPEC_PATH = "app/schemas/openapi.yml".freeze

  def initialize(app)
    @app = app
    spec = OpenapiFirst.load(SPEC_PATH)
    @response_validator = OpenapiFirst::ResponseValidator.new(spec)
    @request_validator = OpenapiFirst::RequestValidation.new(->(_env) {}, spec: SPEC_PATH, raise_error: true)
  end

  def call(env)
    request = Rack::Request.new(env)
    response = @app.call(env)

    if request.path.starts_with?(API_PATH_PREFIX)
      begin
        @request_validator.call(env)
        @response_validator.validate(request, response)
      rescue OpenapiFirst::NotFoundError
        # Until we've got more of the API documented we can simply ignore
        # unspecified routes.
      rescue => e
        raise e unless Rails.env.production?

        MyLogger.log(
          "openapi.request_validation.error",
          path: request.path,
          method: request.env["REQUEST_METHOD"],
          error_message: e.message
        )
      end
    end

    response
  end
end
```

**Comment by ahx** [comment]
@twe4ked Cool!

**Comment by gjtorikian** [comment]
@twe4ked Thanks for sharing that snippet. <3

**Comment by ahx** [comment]
I‘ll close this. Thanks for the insights.

**Comment by ahx** [comment]
FYI: There will be new formalized way to do request/response validation outside of middlewares. See https://github.com/ahx/openapi_first/pull/202#issue-2044500441
