### ISSUE TITLE
Capture names affects finding definitions for nested routes

### ISSUE THREAD

**Issue by twe4ked** [ahx/openapi_first#155]
We had a surprising issue that lead us to `hanami/router` (see this issue: https://github.com/hanami/router/issues/252) where defining routes with different capture names can lead to definitions not being found for nested paths.

Given the following paths:

```
/foo/{id}
/foo/{foo_id}/bar
```

The second route won't be found by the router. Luca suggested adding the `/foo/{foo_id}/bar` route first so it matches earlier.

I see a few options:

1. Do nothing, maybe document the behaviour in the README to tell people not to mix capture names
2. Order the paths intelligently before building the router
3. Warn while building the router if there are path conflicts

Any other ideas?

**Comment by ahx** [comment]
Hey @twe4ked, thanks for posting that here! I would like to have this just work without developers even knowing about it. So if we cannot solve this in hanami/router, I would like to solve it here. So option 2 sounds like an easy way out. 

Can you create a PR with a failing test for this, maybe?

**Comment by ahx** [comment]
This is trickier than I thought. I was thinking we can work around this just by sorting the routes as mentioned in https://github.com/hanami/router/issues/252, but there is more to it. See https://github.com/hanami/router/issues/255 🤔

**Comment by ahx** [comment]
Solved on main
