### ISSUE TITLE
Manual request/response validation

### ISSUE THREAD

**Issue by ahx** [ahx/openapi_first#195]
The idea is to programatically validate requests/responses.

See also https://github.com/ahx/openapi_first/discussions/169#discussioncomment-5517717 https://github.com/ahx/openapi_first/issues/140.

Api proposal: 
```ruby
OpenapiFirst::RequestValidator.new('my/openapi.yaml')

request = Rack::Request.new(env)
validator.validate(request)  # Returns an object with details about the validation result (error?, schema, data, etc.)
validator.validate!(request) # Raises an exception if request is invalid
```

UPDATE: See [Variant 1 ](https://github.com/ahx/openapi_first/issues/195#issuecomment-1838166547)

**Comment by MrBananaLord** [comment]
That looks great!

I suppose the `validator.validate(request)` will handle all descendants of `OpenapiFirst::Error` and return them as a list of validation errors? :)

**Comment by ahx** [comment]
I would rather go the other way around and  `catch`ing and returning things in `.validate` and raise exception in `.validate!`, but that's just implementation details.

**Comment by twe4ked** [comment]
Thanks for this @ahx! Variant 1 looks good to me, good that it should be future proof for OpenAPI 4.0 too. 💯

**Comment by ahx** [comment]
Should be solved with https://github.com/ahx/openapi_first/pull/202
