### ISSUE TITLE
Expose webhooks

### ISSUE THREAD

**Issue by gjtorikian** [ahx/openapi_first#280]
OpenAPI 3.1 has [a `webhooks` key](https://swagger.io/specification/#oas-webhooks) in addition to `paths`. Could this be expose for completeness to the spec's sake?

I wanted to try implementing this myself but didn't know where to begin. It might be as simple as adding a new ivar here:

https://github.com/ahx/openapi_first/blob/49a592e44325f169b6632823467203886915fa9b/lib/openapi_first/definition.rb#L23

**Comment by ahx** [comment]
Hi. Can you tell me a little about the use case? I would like to have good support for OAS webhooks, but I did not use them, yet. So knowing about your use case would be helpful.

Currently the gem is focused on request and response validation and does not have a represention for all parts of an OpenAPI document (components, servers, info etc.). The interface is geared toward request/response validation. But I think adding an interface for webhooks would be interesting.

**Comment by ahx** [comment]
What do you think about adding `Definition#[]` to access the raw Hash? ([See PR](https://github.com/ahx/openapi_first/commit/811e617745765c59b799808a4e3403acd4686075)) That way you would have access to all parts of the OpenAPI Document-Hash. 
However this won't add any help to validate webhook requests or the like.

**Comment by gjtorikian** [comment]
That's actually enough for my use case! :)

To be more specific, my file looks like this:

```json
    "webhooks": {
        "conversation-created": {
            "$ref": "components/schemas/events/conversation/created.json"
        },
        "conversation-updated": {
            "$ref": "components/schemas/events/conversation/updated.json"
        },
...
```

I just wanted to be able to do `schema["webhooks"].keys` to validate the list of documented webhooks.

**Comment by ahx** [comment]
Version 2.1.0 has just been released which includes `Definition#[]`. I'll close this issue because that should meet the use case. 
Thanks for the report @gjtorikian.

**Comment by gjtorikian** [comment]
Thank you!
