### ISSUE TITLE
Invalid JSON not gracefully handled

### ISSUE THREAD

**Issue by Fruetel** [ahx/openapi_first#73]
When providing a post body with invalid JSON (i.e. a trailing ,), I get an error 500 with a stack trace in the response instead of well formatted JSON error response:

```
MultiJson::ParseError: expected array element, not an array close (data.attributes.queueIds) at line 7, column 8 [parse.c:554]
	/Users/thomas.fruetel/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/multi_json-1.14.1/lib/multi_json/adapters/oj.rb:34:in `load'
	/Users/thomas.fruetel/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/multi_json-1.14.1/lib/multi_json/adapters/oj.rb:34:in `load'
	/Users/thomas.fruetel/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/multi_json-1.14.1/lib/multi_json/adapter.rb:21:in `load'
	/Users/thomas.fruetel/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/multi_json-1.14.1/lib/multi_json.rb:122:in `load'
	/Users/thomas.fruetel/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/openapi_first-0.6.9/lib/openapi_first/request_validation.rb:47:in `parse_and_validate_request_body!'
...
```

Feel free to contact me on Slack/Discord if you need more detailed instructions to reproduce this.

**Comment by ahx** [comment]
Thank you @Fruetel. This has been [fixed](https://github.com/ahx/openapi_first/pull/77) in version 0.10.2.
It now returns a 400 status with an error that says `{ title: 'Failed to parse body as JSON' }`. When running the app server in development or test mode, it also includes a more detailed error message from the underlying JSON library (like `{detail: "unexpected token at '{fo},'"}`).
